name: sdl_gamepad
description: A Dart-friendly, cross-platform gamepads API that wraps SDL3 via the sdl3 package
version: 1.1.0
repository: https://github.com/Levi-Lesches/sdl_gamepad

environment:
  sdk: ^3.5.0

dependencies:
  sdl3: ^0.1.34
  ffi: ^2.1.3
  collection: ^1.18.0

dev_dependencies:
  very_good_analysis: ^6.0.0
