name: sdl_gamepad
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  sdl3: ^0.1.31
  ffi: ^2.1.3
  collection: ^1.18.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
